# Visualization {#visualization}

## Maps and GIS

GIS: **G**eographic **I**nformation **S**ystem

Readings: https://bookdown.org/robinlovelace/geocompr/intro.html, @Bivand2013

### Longitudes, latitudes and CRS

Reading: https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf

CRS: **C**oordinate **R**eference **S**ystem

EPSG Geodetic Parameter Dataset: structured dataset of Coordinate Reference Systems and Coordinate Transformations (http://www.epsg-registry.org/)

### Vector data and shapefiles

Reading: https://bookdown.org/robinlovelace/geocompr/spatial-data-operations.html#spatial-operations-on-vector-data

### Raster data

Reading: https://bookdown.org/robinlovelace/geocompr/spatial-data-operations.html#spatial-operations-on-raster-data

### Backends

#### `GDAL`

GDAL: **G**eospatial **D**ata **A**bstraction **L**ibrary

https://en.wikipedia.org/wiki/GDAL#Software_using_GDAL/OGR

#### `GEOS`

GEOS: **G**eometry **E**ngine - **O**pen **S**ource

https://en.wikipedia.org/wiki/JTS_Topology_Suite#Applications_Using_GEOS

### R as a GIS: packages

https://cran.r-project.org/web/packages/sp/

#### `rgdal`

`rgdal`: Bindings for the 'Geospatial' Data Abstraction Library

Provides bindings to the 'Geospatial' Data Abstraction Library ('GDAL') (>= 1.6.3) and access to projection/transformation operations from the 'PROJ.4' library. The 'GDAL' and 'PROJ.4' libraries are external to the package, and, when installing the package from source, must be correctly installed first. Both 'GDAL' raster and 'OGR' vector map data can be imported into R, and 'GDAL' raster data and 'OGR' vector data exported. Use is made of classes defined in the 'sp' package. Windows and Mac Intel OS X binaries (including 'GDAL', 'PROJ.4' and 'Expat') are provided on 'CRAN'.

https://cran.r-project.org/web/packages/rgdal/

#### `rgeos`

`rgeos`: Interface to Geometry Engine - Open Source ('GEOS')

Interface to Geometry Engine - Open Source ('GEOS') using the C 'API' for topology operations on geometries. The 'GEOS' library is external to the package, and, when installing the package from source, must be correctly installed first. Windows and Mac Intel OS X binaries are provided on 'CRAN'.

https://cran.r-project.org/web/packages/rgeos/

#### `proj4`

`proj4`: A simple interface to the PROJ.4 cartographic projections library

A simple interface to lat/long projection and datum transformation of the PROJ.4 cartographic projections library. It allows transformation of geographic coordinates from one projection and/or datum to another.

https://cran.r-project.org/web/packages/proj4/

#### `sf`

`sf`: Simple Features for R

Support for simple features, a standardized way to encode spatial vector data. Binds to GDAL for reading and writing data, to GEOS for geometrical operations, and to Proj.4 for projection conversions and datum transformations.

https://cran.r-project.org/web/packages/sf/

#### `sp`

`sp`: Classes and Methods for Spatial Data

Classes and methods for spatial data; the classes document where the spatial location information resides, for 2D or 3D data. Utility functions are provided, e.g. for plotting data as maps, spatial selection, as well as methods for retrieving coordinates, for subsetting, print, summary, etc.

https://cran.r-project.org/web/packages/sp/

#### `ggmap`

`ggmap`: Spatial Visualization with ggplot2

A collection of functions to visualize spatial data and models on top of static maps from various online sources (e.g Google Maps and Stamen Maps). It includes tools common to those tasks, including functions for geolocation and routing.

https://cran.r-project.org/web/packages/ggmap/

#### `leaflet`

`leaflet`: Create Interactive Web Maps with the JavaScript 'Leaflet' Library

Create and customize interactive maps using the 'Leaflet' JavaScript library and the 'htmlwidgets' package. These maps can be used directly from the R console, from 'RStudio', in Shiny apps and R Markdown documents.

https://cran.r-project.org/web/packages/leaflet/

https://rstudio.github.io/leaflet/

#### Pythonic world

https://pypi.python.org/pypi/GDAL

https://pypi.python.org/pypi/geos

## Principles of visualization

Guest lecture (James Honaker)

